# Generated by Django 4.0.3 on 2022-03-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_remove_profile_adderss_profile_adderssline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Adderssline',
            new_name='AdderssLine',
        ),
    ]
