# Generated by Django 4.0.3 on 2022-03-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_rename_adderssline_profile_adderssline'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='QuesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=255)),
                ('Options', models.TextField(max_length=255)),
                ('Correct', models.CharField(max_length=4)),
                ('Point', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.category')),
            ],
            options={
                'db_table': 'quesset',
            },
        ),
    ]
