# Generated by Django 4.0.1 on 2022-04-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_category_quesset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='LastLogin',
        ),
        migrations.AddField(
            model_name='master',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
