# Generated by Django 4.0.1 on 2022-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_alter_category_options_remove_master_lastlogin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesset',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quesset',
            name='LastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
