# Generated by Django 4.0.1 on 2022-04-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_remove_quesset_correct_remove_quesset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionset',
            name='QuesSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quesset'),
        ),
    ]
